### ISSUE TITLE
Again remove Tag(s)?

### ISSUE THREAD

**Issue by erkinsergey** [pear/Services_Openstreetmap#31]
I installed the version Services_OpenStreetMap-1.0.0RC1. 
My task is to edit tags. I found that I can change tags using **Object::setTag** and **Object::setTags**. It work fine:
```
$config = [
    'adapter'     => 'HTTP_Request2_Adapter_Curl',
    'api_version' => '0.6',
    'password'    => 'password',
    'server'      => 'http://my.osm.server',
    'User-Agent'  => 'Services_OpenStreetMap',
    'user'        => 'user',
  ];

  $osm = new Services_OpenStreetMap($config);

  try {
      $node = $osm->getNode(146679);

      if ($node) {
          $changeset = $osm->createChangeset();

          $changeset->begin("Test change tags via API");
          $node->setTags([
            'name'     => 'test API',
            'power'    => 'pole',
          ]);

          $changeset->add($node);

          $changeset->commit();
      }
  }
  catch (Exception $e) {
      echo $e->getMessage();
  }
```
But I can not delete tags using **Object::setAllTags([])**, **Object::removeTag(s)**. These methods leave empty changeset.
I found that only the **Object::setTag** method changes the internal **dirty** variable, which affects the operations in changesets.

Maybe I'm doing wrong?

**Comment by kenguest** [comment]
I think you unearthed a bug! I'll try to look into this later on today.

**Comment by kenguest** [comment]
@erkinsergey, would you mind confirming this is fixed now please?

**Comment by erkinsergey** [comment]
During the creation of this issue, I have slightly changed the task. Now I do not need to delete tags, I just need to change the values ​​of existing tags.
Therefore, the existing working functionality suits me perfectly and I can close the issue.

However, I tried to test the work of **removeTags** and got an error. My code:
```
$config = [
    'adapter'         => 'HTTP_Request2_Adapter_Curl',
    'api_version'     => '0.6',
    'password'        => 'password',
    'server'          => 'https://my_local_osm_server',
    'User-Agent'      => 'Services_OpenStreetMap',
    'user'            => 'user',
    'ssl_verify_peer' => FALSE,
    'ssl_verify_host' => FALSE,
  ];

  $osm = new Services_OpenStreetMap($config);
  $node = $osm->getNode(147075);
  if ($node) {
          $changeset = $osm->createChangeset();

         $changeset->begin("Test change tags via API");
        // the node 147075 have tags 'some' and 'tag2'
         $node->removeTags(['some', 'tag2']);

         $changeset->add($node);

          $changeset->commit();
      }
     print_r($node->getTags());
```
Result - empty changeset on OSM-server (with field num_changes = 0) and catched exception:
```
message: Error posting changeset,
file: Services/OpenStreetMap/Changeset.php
line: 353,
code: 400
```
In this case, xml for changes looks like this:
```
<osmChange version='0.6' generator='Services_OpenStreetMap'><><node id="147075" changeset="14140" timestamp="2018-09-12T06:35:39Z" version="4" visible="true" user="user" uid="3" lat="47.1728333" lon="38.8641021" action="">
    <tag k="caption" v="My Caption"/>
    <tag k="power" v="pole"/>
    <tag k="some" v="new_val"/>
    <tag k="state" v="actual"/>
    <tag k="tag2" v="tag2_val"/>
  </node></>
</osmChange>
```
Perhaps there really is a mistake.
As I understand it, instead of empty tags, the tag should be 'modified'.

**Comment by dktue** [comment]
Apparently, this is still not working, I'm having the same issue. When removing a tag, nothing happens on the OSM-side.

**Comment by erkinsergey** [comment]
You need to create a new Issue. I closed this for the reason described above.

**Comment by dktue** [comment]
I created #42
